### ISSUE TITLE
Understand and interpret the WHILE loop

### ISSUE THREAD

**Issue by HennieBez** [HennieBez/R4DS_LearningCurve#2]
The R4DS only briefly touches on `while` loops.

Is this a good investment to be accustomed to ?

How often do we use it ?

**Comment by csrvermaak** [comment]
@HennieBez  - I think a `for` loop is better practise - but sometimes you get stuck, and you need a special tool... you will know when you need a while loop. I will explain it to you :)

**Comment by HennieBez** [comment]
Thank you @csrvermaak 

Kind regards
